<template>
  <svg
    width="1.6em"
    height="1.6em"
    viewBox="0 0 20 20"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xml:space="preserve"
    style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;"
    class="share-circle-checkmark"
  >
    <circle
      cx="10"
      cy="10"
      r="8.5"
      style="fill:none;stroke:currentColor;stroke-width:var(--strokeWidth)"
    />
    <path
      d="M6,11L8.5,13.5L15,7"
      style="fill:none;stroke:currentColor;stroke-width:var(--strokeWidth)"
    />
  </svg>
</template>