const t = (new Date()).toLocaleString('en-AU')
const fakeEmail = 'lee+test_'+t.replace(/[^a-z0-9]/g, '')+'@brightlabs.com'


export default {
  full_name: 'Lee test '+t,
  address: '123 Fake Street',
  suburb: 'Melbourne',
  org_name: 'Bright Labs',
  comments: 'This is a test',
  first_name: 'Bright Labs',
  last_name: 'Lee test '+t,
  email: fakeEmail,
  phone: '0415419771',
  mobile: '0415419771',
  postcode: '3057',
  living_with_pcos: 'Yes',
  heard_about_via: 'Other',
  consent: true,
  gender: 'Male',
  deliver_cald_q: 'No',
  computer_access: 'Yes',
  internet_access: 'Yes',
  existing_provider: 'Yes',
  postal_as_above: 'Yes',
  contact_method: 'Email',
  qualification: 'Other',
  other_qualification: 'This is a test',
  professional_accreditation: 'ESSA',
  work_experience: 'This is a test',
  facilitation_experience: 'This is a test',
  cultural_experience: 'This is a test',
  langauges_other_than_en: 'No',
  Company: 'Company foo - test Bright Labs',
  Street: '123 Fake Street',
  City: 'Newtown',
  PostalCode: '3057',
  Number_of_sites__c: '2',
  Number_of_employees_across_all_sites__c: '77',
  FirstName: 'Lee test '+t,
  LastName: 'LastName test '+t,
  How_did_you_hear_about_the_Life_program__c: 'Word of Mouth',
  Position__c: 'CEO',
  Phone: '0415419771',
  Email: fakeEmail,
  First_preferred_session_date_time_HLS__c: '2028-07-01T23:00:00.000Z',
  Second_preferred_session_date_time_HLS__c: '2028-07-01T23:30:00.000Z',
  Healthy_Living_Session_delivery_method__c: 'Webinar',
  Preferred_languages_HLS__c: 'English',
  Number_of_participants__c: '999',
  event: 'Yes',
  building: 'Test',
  abn: '12345678901',
  describe_org: 'testing',
  position: 'web developer',
  fax: '5551234123',
  manager_as_above: 'Yes',
  manager_first_name: 'Bright Labs',
  manager_last_name: 'Lee test '+t,
  manager_phone: '0415419771',
  manager_mobile: '0415419771',
  manager_email: fakeEmail,
  appropriate_space: 'Yes',
  referral_pathways: 'Test',
  delivery_areas: 'Test',
  data_entry: 'Test',
  community_events: 'Yes',
  pl_insurance: 'Yes',
  pl_insurer: 'Test',
  pi_insurance: 'Yes',
  pi_insurer: 'Test',
  gst_registration: 'Yes',
  facilitator_names: 'Test',
  hca_model_training: 'Yes',
  motivational_interviewing: 'Yes',
}